FROM nvcr.io/nvidia/tritonserver:23.10-py3
RUN pip3 install Werkzeug==2.3.7 flask==2.2.0 -i https://pypi.tuna.tsinghua.edu.cn/simple
RUN pip3 install torch==2.1.2 transformers==4.36.2 sentence_transformers==2.2.2 sacremoses==0.1.1 tritonclient==2.41.0 gevent==23.9.1 geventhttpclient==2.0.2  -i https://pypi.tuna.tsinghua.edu.cn/simple